name: Build and Release

# Build every time we push to main or master, or manually trigger the workflow
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          # this distribution is cached by github actions
          distribution: 'temurin'
          # jdk version to use, specified in pom.xml
          java-version: '21'
          # use the github actions cached jdk if available.
          check-latest: false
      - name: Package client jar
        id: package
        # assume windows x64 as the target platform
        run: mvn -B clean package -P=-lwjgl-natives-linux-amd64,lwjgl-natives-windows-amd64 --file pom.xml --no-transfer-progress
      - name: Publish client artifact
        uses: ./.github/actions/upload_build
        if: ${{ always() && steps.package.outcome == 'success' }}
        with:
          SOURCE_FILE: 'target/opencraft.jar'
          DEST_NAME: 'opencraft.jar'
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-release
          name: auto-release-${{ github.sha }}
          make_latest: true
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            target/opencraft.jar
            src/scripts/opencraft-windows.bat
      - name: Move auto-release tag to current commit
        uses: EndBug/latest-tag@latest
        with:
          ref: auto-release
